### ISSUE TITLE
Policy: Target-specific rules

### ISSUE THREAD

**Issue by ehuss** [rust-lang/spec#44]
What should the policy be around documenting target-specific behavior?

There are several areas where we generally have to refer to targets, but should the spec go so far as to completely specify targets (I suspect no?). If not, then where do we draw the line? How do we say "yes" to one thing, and "no" to another?

Some examples of target-specific things from the reference:
* Conditional-compilation keys (target_os and such)
* target_feature
* instruction_set
* debugger_visualizer
* Type layout
* Linking and symbols
* inline assembly
* windows_subsystem
* ABI's
* `main` behavior (maybe)

**Comment by JoelMarcey** [comment]
I imagine we may have to be more determined to document target-specific behavior somewhere down the line, but for the first iteration of the spec could we just make a policy that we only document target-specific behavior where required for the actual correctness of the specification?
