### ISSUE TITLE
Set up bot for t-spec team to approve PRs, etc.

### ISSUE THREAD

**Issue by JoelMarcey** [rust-lang/spec#53]
Similar to `rfcbot` where you have checkboxes next to members of the `t-spec` team that get checked off for approval/review. This would probably be done only on certain types of issues - rfc like issues, maybe. That would need to be discussed.

**Comment by ehuss** [comment]
@rfcbot poll test

**Comment by ehuss** [comment]
^^ @JoelMarcey Is that what you want?

**Comment by JoelMarcey** [comment]
Yes indeed. 👍

**Comment by JoelMarcey** [comment]
Looks like this works now. We can close this then?

**Comment by ehuss** [comment]
Yep. I asked infra to set up the webhooks so that rfcbot can respond faster in https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/spec.20rfcbot.20webhooks.
