### ISSUE TITLE
Settle on a documentation format

### ISSUE THREAD

**Issue by JoelMarcey** [rust-lang/spec#7]
- What output formats do we want?
- What capabilities do we need in the source format (e.g. in terms of interlinking, other base capabilities, etc.?)

[Typst](https://typst.app/) is a document format written in Rust.

**Comment by ehuss** [comment]
@JoelMarcey I think this can maybe be closed?

**Comment by JoelMarcey** [comment]
Yep. We are settling on mdbook with extensions, including those [provided](https://github.com/rust-lang/spec/pull/13) by @ehuss
